# Generated by Django 5.0.6 on 2026-05-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='custom_menu_html',
            field=models.FileField(blank=True, help_text='Upload your own HTML menu file. If uploaded, this will be shown to customers instead of the auto-generated menu.', null=True, upload_to='custom_menus/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='use_custom_menu',
            field=models.BooleanField(default=False, help_text='Check this to show your uploaded HTML menu to customers.'),
        ),
    ]
