# Generated by Django 5.0.6 on 2026-05-21 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_subscriptionplan_restaurantsubscription'),
        ('restaurants', '0002_restaurant_custom_menu_html_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantsubscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantsubscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menus.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='restaurantsubscription',
            name='restaurant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='restaurants.restaurant'),
        ),
    ]
